library(stringr)
library(readxl)
library(forecast)
library(xts)
library(imputeTS)
library(readr)
library(ggplot2)
library(MLmetrics)
library(fpp2)
library(TTR)
library(dplyr)
library(tidyr)
library(naniar)
library(astsa)
library(zoo)
library(TSA)
library(EnvStats)
library(MASS)
library(tseries)
library(DataCombine)
library(DescTools)
library(gridExtra)
library(smooth)
library(sqldf)
library(mice)
library(mctest)
library(lmtest)
library(car)
library(olsrr)
library(splines)
require(tidyverse)
require(tidymodels)
require(data.table)
require(tidyposterior)
require(tsibble)  #tsibble for time series based on tidy principles
require(fable)  #for forecasting based on tidy principles
require(ggfortify)  #for plotting timeseries
require(forecast)  #for forecast function
require(tseries)
require(chron)
require(lubridate)
require(directlabels)
require(zoo)
require(lmtest)
require(TTR)  #for smoothing the time series
